
on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: run Testing
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: list out the file
      run: ls ${{ github.workspace }}

    - name: Cloning the ikea branch
      run: |
        cd ${{ github.workspace }}
        git clone -b 0.8.3 git@gitlab.com:qorvo/wcon/lps_sw/iot_sdk_ikea.git ikea_0_8_3_branch
      env:  
        TOKEN: ${{ secrets.QORVO_SDK_ACCESS_TOKEN }}

    - name: Remove the branch
      run: |
        rm -rf ikea_0_8_3_branch
   
#    - name: Cloning the Qorvo Branch
#      run: source ${{ github.workspace }}/test/scripts/setup/clone_sdk.sh
#      env:  
#        TOKEN: ${{ secrets.QORVO_SDK_ACCESS_TOKEN }}
      
#    - name: activate
#      run: source ${{ github.workspace }}/test/scripts/setup/activate.sh
      
      
