
on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: run Testing
    runs-on: ubuntu-22.04

    steps:
    - name: Cloning the Qorvo Branch
      run: source ${{ github.workspace }}test/script/setup/clone_sdk.sh
      
    - name: activate
      run: source ${{ github.workspace }}test/script/setup/activate.sh
      
      
