
on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: run Testing
    runs-on: ubuntu-22.04

    steps: 
    - name: Maximize runner disk
      uses: gmij/max-build-space@main
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-android: 'true'
    
    - name: Check out repo
      uses: actions/checkout@v4

    - name: list out the file
      run: ls ${{ github.workspace }}

    - name: Running the docker
      run: source ${{ github.workspace }}/test/scripts/docker/run.sh
      
    - name: Cloning the Qorvo Branch
      run: source ${{ github.workspace }}/test/scripts/setup/clone_sdk.sh
      
    - name: activate
      run: source ${{ github.workspace }}/test/scripts/setup/activate.sh

    - name: Make ComboSwitch Hex
      run: |
        make -f ${{ github.workspace }}/test/sdk/Applications/Combo/Switch/Makefile.Switch_Combo_qpg6200_thread_certified clean
        make -f ${{ github.workspace }}/test/sdk/Applications/Combo/Switch/Makefile.Switch_Combo_qpg6200_thread_certified
      
      
