
on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: run Testing
    runs-on: ubuntu-22.04

    steps: 
    - name: Maximize runner disk
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
        remove-haskell: 'true'
#        remove-cached-tools: 'true'
        
    
    - name: Check out repo
      uses: actions/checkout@v4

    - name: list out the file
      run: ls ${{ github.workspace }}

#    - name: Running the docker
#      run: source ${{ github.workspace }}/test/scripts/docker/run.sh

    - name: install some add-in
      run: |
        sudo apt-get install ccache
        
    - name: Cloning the Qorvo Branch
      run: source ${{ github.workspace }}/test/scripts/setup/clone_sdk.sh
      
    - name: activate
      run: source ${{ github.workspace }}/test/scripts/setup/activate.sh

    - name: activate _2
      run: source ${{ github.workspace }}/test/scripts/setup/activate.sh
        
    - name: Make ComboSwitch Hex
      run: |
        make -f ${{ github.workspace }}/test/sdk/Applications/Combo/Switch/Makefile.Switch_Combo_qpg6200_thread_certified
      
      
