
on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: run Testing
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      
    - name: list out the file
      run: ls ${{ github.workspace }}
      
    - name: Cloning the Qorvo Branch
      run: source ${{ github.workspace }}/test/scripts/setup/clone_sdk.sh
      
    - name: activate
      run: source ${{ github.workspace }}/test/scripts/setup/activate.sh
      
      
