
on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: run Testing
    runs-on: ubuntu-22.04

    steps: 
    - name: Maximize runner disk
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
        remove-haskell: 'true'
#        remove-cached-tools: 'true'
        
    
    - name: Check out repo
      uses: actions/checkout@v4

    - name: list out the file
      run: ls ${{ github.workspace }}

    - name: Running the docker
      run: source ${{ github.workspace }}/test/scripts/docker/run.sh

    - name: Cloning the Qorvo Branch
      run: source ${{ github.workspace }}/test/scripts/setup/clone_sdk.sh
      
    - name: Activate + Compile
      run: source ${{ github.workspace }}/test/scripts/setup/activate.sh
      
      
